[package]
name = "RustL-System"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
minifb = "0.27"
clap = { version = "4.0", features = ["derive"] }
glam = "0.27"
rayon = "1.8"
rfd = "0.14"
dirs = "5.0"
